# open-webui-ingress.yaml
# Purpose: Defines a Kubernetes Ingress to route external traffic to the Open-WebUI
# Service via Traefik, using the existing petersimmons-com-tls certificate for TLS.
# Updated to reference the new https-redirect middleware for HTTP-to-HTTPS redirection.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app: open-webui
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - open-webui.petersimmons.com
    secretName: petersimmons-com-tls
  rules:
  - host: open-webui.petersimmons.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 8080